(module info (lib "infotab.ss" "setup")
(define name "offby1-misc")
(define blurb
  (list "Buncha stuff I find useful"))
(define release-notes '(p "Release engineering?  What's that?"))
(define doc.txt "doc.txt")
(define primary-file "howdy.ss")
(define categories '(misc))
(define scribblings '(("manual.scrbl" ())))
)